project:
  type: website
   
website:
  title: "Zaynab Website"
  navbar:
    background: primary
    search: true
    left:
      - href: home.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: team.qmd
        text: "Team"
      - href: contact_us.qmd
        text: "Contact"
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual

